"""some name handling 4

Revision ID: e14fe17416db
Revises: 49a7399b9172
Create Date: 2026-08-25 01:56:21.418797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14fe17416db'
down_revision: Union[str, None] = '49a7399b9172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_tracks', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('spotify_tracks', 'track_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('spotify_tracks', 'track_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_artist',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_album_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_album_release_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_year',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_month',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_quarter',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'playlist_genre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'playlist_subgenre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'energy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'tempo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'danceability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'loudness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'liveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'valence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'speechiness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'acousticness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'instrumentalness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_popularity',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'duration_ms',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'mode',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'key',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'time_signature',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_spotify_tracks_id'), 'spotify_tracks', ['id'], unique=False)
    op.create_unique_constraint(None, 'spotify_tracks', ['track_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_tracks', type_='unique')
    op.drop_index(op.f('ix_spotify_tracks_id'), table_name='spotify_tracks')
    op.alter_column('spotify_tracks', 'time_signature',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'key',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'mode',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'duration_ms',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_popularity',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'instrumentalness',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'acousticness',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'speechiness',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'valence',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'liveness',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'loudness',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'danceability',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'tempo',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'energy',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'playlist_subgenre',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'playlist_genre',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_quarter',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_month',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'release_year',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_album_release_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_album_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_artist',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('spotify_tracks', 'track_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('spotify_tracks', 'id')
    # ### end Alembic commands ###
